language: node_js

sudo: false

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

env:
  global:
    - GITHUB_REPO: github.com/ProgrammingStyle/java.programming.style.git

before_install:
  - export TZ=Asia/Shanghai

script:
  - yarn run build

after_success:
  - git config user.name "Programming Style"
  - git config user.email "holddie@foxmail.com"
  - git clone https://${GITHUB_REPO} ./old-docs
  - cp -r ./old-docs/.git ./docs 
  - cd ./docs
  - git add -A
  - git commit -m "deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git push --force --quiet "https://ProgrammingRoom:${CI_TOKEN}@${GITHUB_REPO}" master:gh-pages